### PR TITLE
Switched from generateUniqueId skin script to utils method.

### PR DESCRIPTION
**Pull request by reinhardt**
See #114

### CODE REVIEW

**Comment by reinhardt** [comment]
Travis breaks with

```Error: The requirement ('Products.GenericSetup>=2.0.dev0') is not allowed by your [versions] constraint (1.10.0)```

It works with this constraint in coredev. Not sure why it doesn't here... Anyone?

**Comment by reinhardt** [comment]
Just got the hint that Travis config is broken and can be ignored. Will wait for Jenkins instead.

**Comment by reinhardt** [comment]
Removing travis in #116

**Comment by jensens** [comment]
close in favor of #120

**Pull request closed without merging**
