### PR TITLE
Small white space fix to test Travis.

### PR DESCRIPTION
**Pull request by mauritsvanrees**

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
BTW, is Travis really needed? We *are* still testing Archetypes with Jenkins. But once Archetypes is no longer used and supported in Plone in the future, it would be useful. And then it is good to have this working already.

**Comment by gotcha** [comment]
I think that buildout within a repo is the easiest way to run tests. But it is worth only if tests pass. Reason why Travis should monitor the buildout.

**Comment by gotcha** [comment]
Travis tests do run and show the same four broken tests I see on my machine.
I will try to fix this asap.

**Comment by gotcha** [comment]
@mauritsvanrees I cannot find on http://jenkins.plone.org/ where the Archetypes tests are run. I'd like to check if the same 4 tests are also broken.

**Comment by mauritsvanrees** [comment]
On the homepage of Jenkins all tests are green.
On 4.3 they are tested in one Jenkins job together with all other packages (well, one for Python 2.6 and one for 2.7). The `bin/alltests` script from `buildout.coredev` tests them all, with the Archetypes tests running in a [separate group](https://github.com/plone/buildout.coredev/blob/4.3/tests.cfg#L181).
On 5.0 and 5.1 the Archetypes related tests are run in a separate job with the `bin/alltests-at` script, again in a [separate group](https://github.com/plone/buildout.coredev/blob/5.1/tests.cfg#L244).

These are links to the console outputs of the last builds:
- 4.3: http://jenkins.plone.org/job/plone-4.3-python-2.7/lastBuild/console
- 5.0: http://jenkins.plone.org/job/plone-5.0-python-2.7-at/lastBuild/console
- 5.1: http://jenkins.plone.org/job/plone-5.1-python-2.7-at/lastBuild/console
Some of them may still be in progress.

When I use the `buildout.cfg` of this `Products.Archetypes` branch and do `bin/test -m test_pawidgets` I get the same four errors. When I do `bin/test -s Products.Archetypes -m test_pawidgets` in coredev 5.1 I get no errors.

It can be that you need checkouts of CMFPlone or plone.app.widgets or other packages. I see: when I revert commit 935b4cd7fc49f0853e2899fa6b30bcb56382edd3 the tests in the simple buildout pass again. But those changes are needed for the tests to pass with coredev, and with future versions of plone.app.widgets.
That is the drawback of having a separate simple buildout.cfg in a package. You would need to keep that up to date with any changes relevant to coredev. And then you are better off just using coredev.

**Comment by gotcha** [comment]
On the other hand, developing packages separately encourage to think deeper when making changes to avoid unnecessary dependencies.

**Pull request merged**
