### PR TITLE
Switch to new testcase using AT after PloneTestcase is now DX

### PR DESCRIPTION
**Pull request by pbauer**

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
This breaks the [AT tests on 5.1](https://jenkins.plone.org/job/plone-5.1-python-2.7-at/1604/), which still uses Archetypes master.
I have [temporarily reverted](579e89bf95a7227cda0617598ea730027fa56eaa) the checkout of Products.Archetypes on coredev 5.1, which should fix this.

Several options:
1. Create a branch 1.15.x of Products.Archetypes and let 5.1 use that.
2. Edit the Archetypes code changed in here to conditionally import `bbb_at` and if that fails, use `bbb`.

Any preference?

**Comment by pbauer** [comment]
@the second option is much smarter than what I did 🤦‍♂️ 
I think we should do that for all packages mentioned in https://github.com/plone/plone.app.testing/pull/51

**Comment by mauritsvanrees** [comment]
I think that is only needed for packages where the master branch is used in both 5.2 and 5.1. Which is only Products.Archetypes. I am working on that now.

**Comment by mauritsvanrees** [comment]
PR: https://github.com/plone/Products.Archetypes/pull/112

**Pull request merged**
