### PR TITLE
DateWidget, DatetimeWidget (pick-a-date) now able to clear previous

### PR DESCRIPTION
**Pull request by seanupton**
values; fixes inability to clear an already set date or datetime in Archetypes fields.

### CODE REVIEW

**Comment by seanupton** [comment]
I am unsure if this is something we want to also fix for the 1.10.x branch and Plone 5.0.x, as well?  Thoughts?

**Comment by jensens** [comment]
You can always start a Jenkins test-job on your own to test that your pull request (PR) does not break anything. 

Below click on the link to Jenkins
screenshot from 2016-07-25 11 20 06

**log in** with your Github user - if not already done before.

Paste the full **pull request URL** into the text field (if multiple pull requests need to be combined in one run, then one PR URL per line)

Click on **Build**

Jenkins reports back to the pull request(s) on Github in the status box at the bottom.

In Plone we value a lot our testing suite, so we usually never merge pull requests if they have not been tested by Jenkins first.

**Comment by jensens** [comment]
A fix for 5.0.x would be nice to have, but I think its nothing critical.

**Comment by seanupton** [comment]
@jensens @thet @vangheem ... or anyone familiar with mockup widgets and converters for them.  Anyone willing to review/merge?  Checks pass, and if this gets merged, I can move on to implementing this fix (clearing previous dates with no value) for 5.0.x next.

**Comment by vangheem** [comment]
Looks good, thank you!

**Pull request merged**
