### PR TITLE
Remove dependendcy on CMFDefault

### PR DESCRIPTION
**Pull request by tomgross**
Do we need ArchTTWTool? It seems to be used nowhere ...

### CODE REVIEW

**Comment by tomgross** [comment]
seems ok to merge now

**Comment by gforcada** [comment]
@tomgross there seems to be a test failure due to this pull request: http://jenkins.plone.org/job/pull-request/112/

**Comment by tomgross** [comment]
I doubt this is releated to my changes and yes it is in the main branch too: http://jenkins.plone.org/job/plone-5.0-python-2.7/1066/testReport/

**Comment by tisto** [comment]
This is unrelated. @thet broke the build and left it broken.

**Comment by gforcada** [comment]
Then everything should be fine with this one: http://jenkins.plone.org/job/pull-request/113

**Pull request merged**
